//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutUsAdmin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AboutUsAdmin()
        {
            this.AboutUsFAQs = new HashSet<AboutUsFAQ>();
        }
    
        public long AboutUsAdminId { get; set; }
        public Nullable<long> ThemeId { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Description { get; set; }
        public Nullable<long> CompanyDetailId { get; set; }
    
        public virtual ThemeDetail ThemeDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AboutUsFAQ> AboutUsFAQs { get; set; }
    }
}
