//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyDetail
    {
        public long CompanyDetailId { get; set; }
        public string CompanyName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string PinCode { get; set; }
        public string GSTNo { get; set; }
        public string CINno { get; set; }
        public string PhoneNo { get; set; }
        public string EmailId { get; set; }
        public string WebsiteLink { get; set; }
        public string InvoiceLogo { get; set; }
        public string WebsiteLogo { get; set; }
        public string favicon { get; set; }
        public string PaymentGateway { get; set; }
        public string PaymentGatewayKey { get; set; }
    }
}
