//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactUsAdmin
    {
        public long ContactUsAdminId { get; set; }
        public Nullable<long> ThemeId { get; set; }
        public string Address { get; set; }
        public string ContactNo { get; set; }
        public string EmailId { get; set; }
        public string Description { get; set; }
        public string Address1 { get; set; }
        public Nullable<long> CompanyDetailId { get; set; }
        public string Iframe { get; set; }
    
        public virtual ThemeDetail ThemeDetail { get; set; }
    }
}
