//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourierDetail
    {
        public long CourierDetailId { get; set; }
        public Nullable<long> SalesOrderId { get; set; }
        public Nullable<long> CompanyDetailId { get; set; }
        public string CourierName { get; set; }
        public string CourierNo { get; set; }
        public Nullable<System.DateTime> BookedDate { get; set; }
        public string Description { get; set; }
    
        public virtual SalesOrder SalesOrder { get; set; }
    }
}
