//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EcommerceEntities : DbContext
    {
        public EcommerceEntities()
            : base("name=EcommerceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AboutUsAdmin> AboutUsAdmins { get; set; }
        public virtual DbSet<AboutUsFAQ> AboutUsFAQs { get; set; }
        public virtual DbSet<AddDetail> AddDetails { get; set; }
        public virtual DbSet<AdminLogin> AdminLogins { get; set; }
        public virtual DbSet<BrandType> BrandTypes { get; set; }
        public virtual DbSet<CancelledComment> CancelledComments { get; set; }
        public virtual DbSet<CaptchaType> CaptchaTypes { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CompanyDetail> CompanyDetails { get; set; }
        public virtual DbSet<ContactUsAdmin> ContactUsAdmins { get; set; }
        public virtual DbSet<CopyRight> CopyRights { get; set; }
        public virtual DbSet<CouponDetail> CouponDetails { get; set; }
        public virtual DbSet<CourierDetail> CourierDetails { get; set; }
        public virtual DbSet<DeliveryCharge> DeliveryCharges { get; set; }
        public virtual DbSet<DeliveryConfirmation> DeliveryConfirmations { get; set; }
        public virtual DbSet<DiscountDetail> DiscountDetails { get; set; }
        public virtual DbSet<HomeBannerImage> HomeBannerImages { get; set; }
        public virtual DbSet<HomePageSetting> HomePageSettings { get; set; }
        public virtual DbSet<HomeSlider> HomeSliders { get; set; }
        public virtual DbSet<HomeSliderImage> HomeSliderImages { get; set; }
        public virtual DbSet<InvoiceNumber> InvoiceNumbers { get; set; }
        public virtual DbSet<MemberCart> MemberCarts { get; set; }
        public virtual DbSet<MemberDetail> MemberDetails { get; set; }
        public virtual DbSet<MemberOrder> MemberOrders { get; set; }
        public virtual DbSet<MessageAlert> MessageAlerts { get; set; }
        public virtual DbSet<PaymentOption> PaymentOptions { get; set; }
        public virtual DbSet<PrivacyPolicy> PrivacyPolicies { get; set; }
        public virtual DbSet<ProductDetail> ProductDetails { get; set; }
        public virtual DbSet<ProductFeature> ProductFeatures { get; set; }
        public virtual DbSet<ProductImage> ProductImages { get; set; }
        public virtual DbSet<ProductReview> ProductReviews { get; set; }
        public virtual DbSet<ProductStock> ProductStocks { get; set; }
        public virtual DbSet<ProductTecDetail> ProductTecDetails { get; set; }
        public virtual DbSet<ProductVariance> ProductVariances { get; set; }
        public virtual DbSet<SalesOrder> SalesOrders { get; set; }
        public virtual DbSet<SalesOrderItem> SalesOrderItems { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<SocialMedia> SocialMedias { get; set; }
        public virtual DbSet<SocialMediaLink> SocialMediaLinks { get; set; }
        public virtual DbSet<SubCategory> SubCategories { get; set; }
        public virtual DbSet<TaxDetail> TaxDetails { get; set; }
        public virtual DbSet<TermsAndCondition> TermsAndConditions { get; set; }
        public virtual DbSet<TermsAndConditionInvoive> TermsAndConditionInvoives { get; set; }
        public virtual DbSet<ThemeDetail> ThemeDetails { get; set; }
        public virtual DbSet<TodayDeal> TodayDeals { get; set; }
        public virtual DbSet<Variancecolorcode> Variancecolorcodes { get; set; }
        public virtual DbSet<VisitorCount> VisitorCounts { get; set; }
        public virtual DbSet<Wholesaleprice> Wholesaleprices { get; set; }
    }
}
