//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeSlider
    {
        public long HomeSliderId { get; set; }
        public string SliderName { get; set; }
        public Nullable<System.DateTime> CutofDate { get; set; }
        public Nullable<long> IsActive { get; set; }
        public Nullable<long> InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> CompanydetailsId { get; set; }
    }
}
