//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeBannerImage
    {
        public long HomeBannerImageId { get; set; }
        public Nullable<long> HomePageSettingsId { get; set; }
        public string BannerImageURL { get; set; }
        public Nullable<long> CompanyDetailId { get; set; }
    
        public virtual HomePageSetting HomePageSetting { get; set; }
    }
}
