//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceNumber
    {
        public long InvoiceNumberId { get; set; }
        public Nullable<int> InvoiceNumber1 { get; set; }
        public string Companyid { get; set; }
        public string invoiceprefix { get; set; }
    }
}
