//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageAlert
    {
        public long MessageAlertId { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
