//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrivacyPolicy
    {
        public long PrivacyPolicyId { get; set; }
        public string PrivacyPolicies { get; set; }
        public Nullable<long> CompanyDetailId { get; set; }
    }
}
