//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTecDetail
    {
        public long ProductTecDetailsId { get; set; }
        public Nullable<long> ProductId { get; set; }
        public string Description { get; set; }
        public string TechinalDetails { get; set; }
        public Nullable<long> CompanyDetailId { get; set; }
    
        public virtual ProductDetail ProductDetail { get; set; }
    }
}
