//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStock
    {
        public long StockId { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<long> StockCount { get; set; }
        public string ShowToUser { get; set; }
        public string ShowIfNoStock { get; set; }
        public Nullable<long> CompanyDetailId { get; set; }
        public Nullable<long> ProductVarianceId { get; set; }
    
        public virtual ProductDetail ProductDetail { get; set; }
        public virtual ProductVariance ProductVariance { get; set; }
    }
}
