//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderItem
    {
        public long SalesOrderItemId { get; set; }
        public Nullable<long> SalesOrderId { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<decimal> ProductPrice { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> CouponPercentage { get; set; }
        public Nullable<decimal> DiscountPercentage { get; set; }
        public Nullable<decimal> TaxPercentage { get; set; }
        public Nullable<long> CompanyDetailId { get; set; }
        public Nullable<long> ProductVarianceId { get; set; }
    
        public virtual ProductDetail ProductDetail { get; set; }
        public virtual SalesOrder SalesOrder { get; set; }
    }
}
