//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesOrder()
        {
            this.CourierDetails = new HashSet<CourierDetail>();
            this.DeliveryConfirmations = new HashSet<DeliveryConfirmation>();
            this.SalesOrderItems = new HashSet<SalesOrderItem>();
        }
    
        public long SalesOrderId { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<long> MemberId { get; set; }
        public Nullable<decimal> Amoount { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public string DeliveryAddressLine1 { get; set; }
        public string DeliveryAddressLine2 { get; set; }
        public string DeliveryCity { get; set; }
        public string DeliveryState { get; set; }
        public string DeliveryPinCode { get; set; }
        public string DeliveryLandMark { get; set; }
        public string DeliveryName { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> InProgressDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<long> CompanyDetailId { get; set; }
        public string DeliveryContactNo { get; set; }
        public string DeliveryEmail { get; set; }
        public Nullable<System.DateTime> CancelledDate { get; set; }
        public string CancelledComments { get; set; }
        public string CancelledBy { get; set; }
        public Nullable<decimal> OrderDeliveryCharge { get; set; }
        public string OfferType { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public string CouponCode { get; set; }
        public string FreeProductId { get; set; }
        public string PaymentId { get; set; }
        public string InvoiceNo { get; set; }
        public string SalesPersonName { get; set; }
        public string DeliveryMode { get; set; }
        public string DeliveryDate { get; set; }
        public string OrderNotes { get; set; }
        public string PaymentType { get; set; }
        public string DeliveryCharge { get; set; }
        public string Subtotal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourierDetail> CourierDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryConfirmation> DeliveryConfirmations { get; set; }
        public virtual MemberDetail MemberDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesOrderItem> SalesOrderItems { get; set; }
    }
}
