//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaxDetail()
        {
            this.ProductDetails = new HashSet<ProductDetail>();
        }
    
        public long TaxDetailsId { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<long> IsActive { get; set; }
        public string Picture { get; set; }
        public Nullable<long> InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> CompanyDetailId { get; set; }
        public string CategoryId { get; set; }
        public string SubCategoryId { get; set; }
        public string ProductId { get; set; }
        public string CGSTPercentage { get; set; }
        public string SGSTPercentage { get; set; }
        public string IGSTPercentage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDetail> ProductDetails { get; set; }
    }
}
