//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThemeDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThemeDetail()
        {
            this.AboutUsAdmins = new HashSet<AboutUsAdmin>();
            this.ContactUsAdmins = new HashSet<ContactUsAdmin>();
        }
    
        public long ThemeId { get; set; }
        public string ThemeName { get; set; }
        public string ThemeImage { get; set; }
        public string Type { get; set; }
        public Nullable<long> CompanyDetailId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AboutUsAdmin> AboutUsAdmins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactUsAdmin> ContactUsAdmins { get; set; }
    }
}
