//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TodayDeal
    {
        public long TodayDealId { get; set; }
        public Nullable<long> ProductId { get; set; }
        public Nullable<long> CompanyDetailId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> TodayDiscountAmount { get; set; }
    
        public virtual ProductDetail ProductDetail { get; set; }
    }
}
