//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcommerceAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variancecolorcode
    {
        public long VariancecolorcodeId { get; set; }
        public string colorcode { get; set; }
        public Nullable<long> ProductVarianceId { get; set; }
        public Nullable<long> Status { get; set; }
    
        public virtual ProductVariance ProductVariance { get; set; }
        public virtual ProductVariance ProductVariance1 { get; set; }
        public virtual ProductVariance ProductVariance2 { get; set; }
    }
}
